# Generated by Django 5.1a1 on 2024-06-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='billing_address_1',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='billing_address_2',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='billing_country_area',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='billing_country_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='billing_email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='billing_first_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='billing_last_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='billing_postcode',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='captured_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer_ip_address',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='fraud_message',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='fraud_status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='token',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='total',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='variant',
        ),
    ]
