# Generated by Django 5.1a1 on 2024-06-24 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_cart_cartitem_simulatedpayment_delete_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimulatedPayment',
        ),
    ]
