# Generated by Django 5.0.6 on 2024-06-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='workshop',
            name='duration',
            field=models.CharField(default='90 minutes', max_length=50),
        ),
    ]
