# Generated by Django 5.0.6 on 2024-06-12 22:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_workshop_category_workshop_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='WorkshopDateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates_times', to='workshops.workshop')),
            ],
        ),
    ]
