# Generated by Django 5.0.6 on 2024-06-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_workshop_date_workshopdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopdatetime',
            name='time_choice',
            field=models.CharField(choices=[('10am', '10 am'), ('11am', '11 am'), ('12noon', '12 noon'), ('2pm', '2 pm'), ('3pm', '3 pm'), ('4pm', '4 pm')], default='10 AM', max_length=20),
        ),
    ]
