# Generated by Django 5.0.6 on 2024-06-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_alter_workshopdatetime_time_choice_booking_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workshop_images/'),
        ),
    ]
