# Generated by Django 5.1a1 on 2024-06-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_profile_picture'),
        ('workshops', '0007_delete_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='booked_workshops',
            field=models.ManyToManyField(blank=True, to='workshops.workshop'),
        ),
    ]
